$(document).ready(function(){
  $(".aboutHidden").click(function(){
    $(".aboutHidden").toggle();
    $(".aboutShowing").toggle();
  });
  $(".aboutShowing").click(function(){
    $(".aboutHidden").toggle();
    $(".aboutShowing").toggle();
  });
  $(".eduHidden").click(function(){
    $(".eduHidden").toggle();
    $(".eduShowing").toggle();
  });
  $(".eduShowing").click(function(){
    $(".eduHidden").toggle();
    $(".eduShowing").toggle();
  });
  $(".interestsHidden").click(function(){
    $(".interestsHidden").toggle();
    $(".interestsShowing").toggle();
  });
  $(".interestsShowing").click(function(){
    $(".interestsHidden").toggle();
    $(".interestsShowing").toggle();
  });
  $(".moeHidden").click(function(){
    $(".moeHidden").toggle();
    $(".moeShowing").toggle();
  });
  $(".moeShowing").click(function(){
    $(".moeHidden").toggle();
    $(".moeShowing").toggle();
  });
  $(".sillyHidden").click(function(){
    $(".sillyHidden").toggle();
    $(".sillyShowing").toggle();
  });
  $(".sillyShowing").click(function(){
    $(".sillyHidden").toggle();
    $(".sillyShowing").toggle();
  });
  $(".vacaHidden").click(function(){
    $(".vacaHidden").toggle();
    $(".vacaShowing").toggle();
  });
  $(".vacaShowing").click(function(){
    $(".vacaHidden").toggle();
    $(".vacaShowing").toggle();
  });
  $(".shroomHidden").click(function(){
    $(".shroomHidden").toggle();
    $(".shroomShowing").toggle();
  });
  $(".shroomShowing").click(function(){
    $(".shroomHidden").toggle();
    $(".shroomShowing").toggle();
  });
});
